AltCloud\Instance3MediaBundle\Entity\Media:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    title:
      type: string
      length: 255
      nullable: true
    description:
      type: text
      nullable: true
    datetime:
      type: datetimetz
  lifecycleCallbacks: {  }
  manyToOne:
    gallery:
      targetEntity: Gallery
      inversedBy: media
      joinColumn:
        name: gallery_id
        referencedColumnName: id
  oneToMany:
    formats:
      targetEntity: Format
      mappedBy: media
      cascade: [persist]
  oneToOne:
    thumbnail:
      targetEntity: Format